name: Node.js CI

on:
    push:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
            - name: Install Eslint
              run: |
                  npm ci
                  npm install eslint
            - run: npm run build --if-present
            - name: Eslint working flow
              run: |
                  npm run eslint
                  npm run format
                  npm run stylelint
